### ISSUE TITLE
Tests fail with perl 5.23.4

### ISSUE THREAD

**Issue by eserte** [benkasminbullock/Text-Fuzzy#16]
Partial test output:
```
panic: stack_grow() negative count (-1) at t/private-functions.t line 32.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 3.
t/private-functions.t ... 
```
More information: https://rt.perl.org/Ticket/Display.html?id=126472

**Comment by benkasminbullock** [comment]
Thanks for the pointer to that discussion. I have fixed in this commit:

https://github.com/benkasminbullock/Text-Fuzzy/commit/b7b82ff410d2ca0f357d7812078ad886024015bd

That should resolve the issue, but if not please feel free to open this again.

Thanks.

**Comment by eserte** [comment]
Looks good so far: http://matrix.cpantesters.org/?dist=Text-Fuzzy+0.24
